parameters:
  - name: ArmTemplatesPath
    type: string
  - name: ServicesTemplatesPath
    type: string
  - name: ScriptsPath
    type: string

steps:
  - publish: ${{ parameters.ArmTemplatesPath }}
    artifact: ArmTemplates

  - publish: ${{ parameters.ServicesTemplatesPath }}
    artifact: Services

  - publish: $(System.DefaultWorkingDirectory)/DevOps/Tasks/Utils
    artifact: scripts

#  - publish: ${{ parameters.ScriptsPath }}
#    artifact: Scripts