variables:
  Environment: 'Test' 
  AdoEnvironment: 'test-data'
 # tenantid 89397abe-df61-48a3-abe3-efc403bca4bd

  # GHUB lz variables
  SubscriptionIdGHUB: "1943f6e4-c483-433c-a82b-cc02e45ad73c"
  ResourceGroupNameGHUB: "lz-ghub-${{ lower(variables.Environment) }}-uks-rg-01"
  DataFactoryNameGHUB: "lz-ghub-${{ lower(variables.Environment) }}-uks-adf-01"
  AzureDataFactoryPipelinesArmTemplateParametersGHUBAdf01: "Services/DataAnalytics/ARMTemplateParametersForFactory01${{ variables.Environment }}.json" #this file doesn't exist for dev

  # Arm template parameter files
  AzureKeyVaultArmTemplateParametersData: "ArmTemplates/Keyvault/Parameters/${{ upper(variables.Environment) }}/AzureKeyVault.Data.parameters.json"
  AzureSqlServerParametersData: "ArmTemplates/AzureSQL/Parameters/${{ upper(variables.Environment) }}/AzureSQL.Data.parameters.json"
  AzureDataFactoryParametersData: "ArmTemplates/DataFactory/Parameters/${{ upper(variables.Environment) }}/AzureDataFactory.parameters.json"
  AzureLogAnalyticsParameters: "ArmTemplates/LogAnalytics/Parameters/${{ upper(variables.Environment) }}/LogAnalytics.parameters.json"

 # Sql server variable for server 23
  AzureSqlServerName_23: "lz-cgr-${{ lower(variables.Environment) }}-uks-sqldb-23" 
 
  # DATransactions vars
  SQLBuildSourceFolder_dbLida: "SQL DBs/DatabaseLIDA"
  AzureSqlServerDADbAddress: ${{ lower(variables.AzureSqlServerName_23) }}.database.windows.net #comes from the variable above
  DADatabaseName: "DATransactions"

  # dafac source database vars
  SQLBuildSourceFolder_dbfacStuffSource: "SQL DBs/dafacstuffuks"
  AzureSqlServerDbAddress_facstuff_source: ${{ lower(variables.AzureSqlServerName_23) }}.database.windows.net #comes from the variable above
  DatabaseName_facstuff_source: "dba-fac-stf-source"

  # dafac target database vars
  SQLBuildSourceFolder_dbfacStuffTarget: "SQL DBs/dafacstuffuks-target"
  AzureSqlServerDbAddress_facstuff_target: ${{ lower(variables.AzureSqlServerName_23) }}.database.windows.net #comes from the variable above
  DatabaseName_facstuff_target: "dba-facstuff-target"

  # Sql server variable for server ghub
  AzureSqlServerName_ghub: "sqlsrv-yqnh5nxtq5rhi-${{ lower(variables.Environment) }}.database.windows.net" 
