variables:
  Environment: 'Prod' 
  AdoEnvironment: 'prod-data'

  # Data lz variables
  SubscriptionIdData: "1943f6e4-c483-433c-a82b-cc02e45ad73c"
  ResourceGroupNameData: "lz-ghubvse-${{ lower(variables.Environment) }}-uks-rg-01"
  DataFactoryNameData: "lz-ghubvse-${{ lower(variables.Environment) }}-uks-adf-01"
  AzureDataFactoryPipelinesArmTemplateParametersDataAdf01: "Services/DataAnalytics/ARMTemplateParametersForFactory01${{ variables.Environment }}.json" #this file doesn't exist for dev

  # Arm template parameter files
  AzureKeyVaultArmTemplateParametersData: "ArmTemplates/Keyvault/Parameters/${{ upper(variables.Environment) }}/AzureKeyVault.Data.parameters.json"
  BicepStorageParametersData: "ArmTemplates/Bicep-parameters/${{ upper(variables.Environment) }}/bicep.parameters.json"
  AzureSqlServerParametersData: "ArmTemplates/AzureSQL/Parameters/${{ upper(variables.Environment) }}/AzureSQL.Data.parameters.json"
  AzureDataShareParametersData: "ArmTemplates/Datashare/Parameters/${{ upper(variables.Environment) }}/AzureDataShare.Data.parameters.json"

  # DATransactions vars
  SQLDevelopmentPathDAtransDb: "SQL DBs/DatabaseLIDA/DatabaseLIDA.sqlproj"
  AzureSqlServerNameDA: "lz-cgr-${{ lower(variables.Environment) }}-uks-sqldb-23" 
  AzureSqlServerDADbAddress: ${{ lower(variables.AzureSqlServerNameDA) }}.database.windows.net #comes from the variable above
  DADatabaseName: "DATransactions"