variables:
  Environment: 'Dev' 

  # Int shared platform lz variables
  SubscriptionIdInt: "3be2ce56-4a5f-4034-88d7-2953d1819ed3"
  ResourceGroupNameIntSharedPlatform: "lz-ghubvse-${{ lower(variables.Environment) }}-uks-rg-01"
  AutomationAccountName : "lz-ghubvse-${{ lower(variables.Environment) }}-uks-automationacc-01"

  

 